### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/draft-guide-jax-rs-reactive-client#13] opened 2019-09-09 15:00 UTC
Since this is a reactive guide, I suggest you describe reactive programming.  I also suggest you explain what is improved over asynchronous programming. 

 I may be off base.  I would think that this guide would show how do improve an asynchronous programming application to use reactive programming and why.

You might even want to use a third party RxJava.

Add Docker as a Prerequisites.

You may want to add a reference to https://openliberty.io/blog/2019/04/10/jaxrs-reactive-extensions.html?fbclid=IwAR00IgA2lwRsp0_lRTOVTibTw7oZTwkHr_pCDLXKxIxwA8EgE_xrxk22r5A

I tried **mvn clean install** from the finish directory Failed:

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   SystemEndpointTest.testGetProperties:124 expected:<200> but was:<404>
[ERROR]   SystemEndpointTest.testRunJob:155 No records processed
[INFO]
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0

[INFO] Reactor Summary:
[INFO]
[INFO] reactive-demo 1.0-SNAPSHOT ......................... SUCCESS [  3.695 s]
[INFO] models ............................................. SUCCESS [ 15.872 s]
[INFO] system ............................................. FAILURE [09:06 min]
[INFO] inventory .......................................... SKIPPED
[INFO] job ................................................ SKIPPED
[INFO] gateway 1.0-SNAPSHOT ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by gkwan-ibm** [comment] 2019-09-18 14:30
the test failure was caused by https://github.com/bitnami/bitnami-docker-kafka/issues/64 which was fixed but not sure in the latest release yet or not.

**Comment by jonathanxue** [comment] 2019-12-11 16:11
- test failures addressed
- docker prerequisite added
- other issues addressed in #18

**Closed by jonathanxue** 2019-12-11 16:11 UTC
